name: Running Web FashionHub Tests
run-name: "[${{ github.event.inputs.environment }}] [${{ github.event.inputs.browser }}] Web Automation Tests"
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Environment
        type: choice
        options:
          - production
          - staging
      browser:
        required: false
        description: Browser
        type: choice
        options:
          - chrome
          - firefox
          - safari

jobs:
  playwirght-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests
        run: mvn clean test -Denv=${{ github.event.inputs.environment }} -Dbrowser=${{ github.event.inputs.browser }}

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_history: allure-history
          allure_results: reports/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh_pages
          publish_dir: allure-history

      - name: Upload CSV Report
        uses: actions/upload-artifact@v4.4.3
        if: always()
        with:
          name: Open PRs Reports
          path: reports/*.csv