name: Run Tests
run-name: "[${{ github.event.inputs.environment }}] [${{ github.event.inputs.browser }}] Web Automation Tests"
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Environment
        type: choice
        options:
          - production
          - staging
      browser:
        required: false
        description: Browser
        type: choice
        options:
          - chrome
          - firefox
          - webkit

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Tests
        run: mvn clean test -Denv=${{ github.event.inputs.environment }} -Dbrowser=${{ github.event.inputs.browser }}
      - name: Upload Report
        uses: actions/upload-artifact@v4.4.3
        if: always()
        with:    
          name: Cucumber Report
          path: reports/cucumber-report/*
      - name: Upload CSV Report
        uses: actions/upload-artifact@v4.4.3
        if: always()
        with:
          name: Open PRs Reports
          path: reports/*.csv